full_test

diff --git a/tests/test_actions b/tests/test_actions
--- a/tests/test_actions
+++ b/tests/test_actions
@@ -3,54 +3,54 @@
 
 function test_fucntions {
 
-	# source $(pwd)/scripts/genome_indexing
+	source $(pwd)/scripts/genome_indexing
 
-	# echo ''
-	# echo -e '\033[1;32m Test for genome downloading...'
-	# echo ''
+	echo ''
+	echo -e '\033[1;32m Test for genome downloading...'
+	echo ''
 
-	# species=human
-	# #config
-	# source $(pwd)/requirements_file/genome.conf
-	# human_annotation=$human_annotation
+	species=human
+	#config
+	source $(pwd)/requirements_file/genome.conf
+	human_annotation=$human_annotation
 
-	# species=$(echo $species | tr '[:upper:]' '[:lower:]')
-	# source=$(pwd)/scripts
-	# input_human=$(pwd)/genome/$species/annotation_human.gtf
+	species=$(echo $species | tr '[:upper:]' '[:lower:]')
+	source=$(pwd)/scripts
+	input_human=$(pwd)/genome/$species/annotation_human.gtf
 
-	# mkdir -p genome
-	# mkdir -p genome/$species
-	# cd genome/$species
-	# wget ${human_annotation} -O annotation.gtf.gz
-	# gunzip annotation.gtf.gz
+	mkdir -p genome
+	mkdir -p genome/$species
+	cd genome/$species
+	wget ${human_annotation} -O annotation.gtf.gz
+	gunzip annotation.gtf.gz
 	
-	# cd ..
-	# cd ..
+	cd ..
+	cd ..
 	
-	# echo -e "\033[0;34m $(date) Creating genome reference files"
-	# create_ref  
+	echo -e "\033[0;34m $(date) Creating genome reference files"
+	create_ref  
 
-	# Rscript $source/genome_prep.R $species $(pwd)/genome/$species/annotation.gtf $(pwd)/genome/$species
+	Rscript $source/genome_prep.R $species $(pwd)/genome/$species/annotation.gtf $(pwd)/genome/$species
 	
-	# echo -e "\033[0;34m $(date) Generating of the intervals"
-	# rna_intervals
+	echo -e "\033[0;34m $(date) Generating of the intervals"
+	rna_intervals
 	
-	# echo -e "\033[0;32m $(date) Process DONE!"
+	echo -e "\033[0;32m $(date) Process DONE!"
 	
-	# check_path=$(pwd)/genome/$species/reduced_annotation.gtf
+	check_path=$(pwd)/genome/$species/reduced_annotation.gtf
 
-	# if [ -f $check_path ]; then
-	# 	echo ''
-	# 	echo ''
+	if [ -f $check_path ]; then
+		echo ''
+		echo ''
     	
-	# 	echo -e '\033[1;32m Test passed successfully'
-	# else
-	# 	echo ''
-	# 	echo ''
+		echo -e '\033[1;32m Test passed successfully'
+	else
+		echo ''
+		echo ''
 		
-    # 	echo -e '\033[1;31m Test failed - genome downloading'
-	# 	exit 1 
-	# fi 
+    	echo -e '\033[1;31m Test failed - genome downloading'
+		exit 1 
+	fi 
 
 
 	
@@ -90,42 +90,42 @@ function test_fucntions {
 	fi 
 
 
-	# cd $(pwd)/projects/test_actions_fq
-	# source config
-	# project_name=$project_name
-	# project_name_mode=$project_name_mode 
-	# READS_LENGHT=$READS_LENGHT 
-	# species=$species 
-	# cell=$cell
-	# marker_path=$marker_path
-	# samples=$samples
+	cd $(pwd)/projects/test_actions_fq
+	source config
+	project_name=$project_name
+	project_name_mode=$project_name_mode 
+	READS_LENGHT=$READS_LENGHT 
+	species=$species 
+	cell=$cell
+	marker_path=$marker_path
+	samples=$samples
 
-	# cd ..
-	# cd ..
-
-
-	# source=$(pwd)/scripts
-	# source $source/analysis_species
-	# seurat 
+	cd ..
+	cd ..
 
 
-	# check_path=$(pwd)/projects/test_actions_fq/results/Report.html
+	source=$(pwd)/scripts
+	source $source/analysis_species
+	seurat 
 
-	# if [ -f $check_path ]; then
+
+	check_path=$(pwd)/projects/test_actions_fq/results/Report.html
+
+	if [ -f $check_path ]; then
 	
-	# 	echo ''
-	# 	echo ''
+		echo ''
+		echo ''
     	
-	# 	echo -e '\033[1;32m All tests passed successfully'
-	# else
-    # 	echo ''
-	# 	echo ''
+		echo -e '\033[1;32m All tests passed successfully'
+	else
+    	echo ''
+		echo ''
 		
-	# 	echo -e '\033[1;31m Test failed - analysis'
-	# 	exit 1 
+		echo -e '\033[1;31m Test failed - analysis'
+		exit 1 
 
 
-	# fi 
+	fi 
 
 
 	# multisamples test
